name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      - name: Hugging Face Sync
        uses: JacobLinCool/huggingface-sync@v1.0.0
        with:
          user: "Amy07amitha"  # Your Hugging Face username
          space: "News_summarization_tts_model"  # Your Hugging Face Space name
          token: ${{ secrets.HF_TOKEN }}  # Hugging Face access token stored as a GitHub secret
          github: ${{ secrets.GITHUB_TOKEN }}  # GitHub Actions token
          emoji: "📰"  # Optional: Emoji for space
          colorFrom: "indigo"  # Optional: Start color for the gradient
          colorTo: "pink"  # Optional: End color for the gradient
          sdk: "streamlit"  # Since you are using Streamlit
          python_version: "3.9"  # Specify Python version
          sdk_version: "1.19.0"  # Compatible Streamlit version
          app_file: "app.py"  # Path to main application file
          fullWidth: true  # Optional: Make it full-width
          pinned: true  # Optional: Pin the space on your profile
