name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Pulls the latest code

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      - name: Set up Hugging Face authentication
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git config --global credential.helper store
          echo "https://huggingface.co:$HF_TOKEN" > ~/.git-credentials
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      - name: Push to Hugging Face Spaces
        run: |
          git clone https://huggingface.co/spaces/Amy07amitha/News_summarization_tts_model hf-space
          rsync -av --exclude=".git" . hf-space/  # Sync files excluding .git
          cd hf-space
          git add .
          git commit -m "Auto-sync from GitHub" || echo "No changes to commit"
          git push origin main
